FROM eclipse-temurin:17-jdk-jammy AS build
USER root

# Install maven
RUN apt-get update && apt-get install -y maven && \
    apt-get install -y python3 && \
    apt-get install -y python3-pip

# Set up working directory
WORKDIR /app

# Copy project files
COPY . .

RUN ls

RUN pip install --no-cache-dir -r script/requirements.txt

RUN mvn clean install

COPY target/*.jar app.jar
EXPOSE 8080


ENTRYPOINT ["java", "-jar", "app.jar"]

