name: ci

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Checkstyle linter
      run: mvn checkstyle:check

    - name: Build Docker image
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      run: |
        docker build --build-arg CODECOV_TOKEN=$CODECOV_TOKEN --tag my-app:latest -f Dockerfile.test .
